### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by thisiszhubq** [xun-xh/yolov5-onnx-pyqt-exe#10]
打包提示如下：
FATAL: Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with --static-libpython=no" if you don't want to install it.
Traceback (most recent call last):
  File "E:\Yolo\test2\yolov5-onnx-pyqt-exe-master\build.py", line 44, in <module>
    movefile(exe_path)
  File "E:\Yolo\test2\yolov5-onnx-pyqt-exe-master\build.py", line 36, in movefile
    shutil.copy(src_path, os.path.join(dst_path, os.path.basename(src_path)))
  File "D:\Anaconda3\envs\Yolo_test\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\Anaconda3\envs\Yolo_test\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Yolo\\test2\\yolov5-onnx-pyqt-exe-master\\build_file\\debug\\Yolo2onnxDetectProjectDemo.dist\\Yolo2onnxDetectProjectDemo.exe'

**Comment by xun-xh** [comment]
不要用conda环境

**Comment by AllenYang00000** [comment]
你好，请问这个问题解决了吗？我也遇到了同样的问题

**Comment by AllenYang00000** [comment]
> 你好，请问这个问题解决了吗？我也遇到了同样的问题

我解决了这个问题。原因是缺少python的核心库libpython。conda install libpython可以解决这个问题。

**Comment by Homecoming48** [comment]
@AllenYang00000 您好，上述这个问题我还是没有解决，是什么原因呢，已经按照您的方法conda install libpython，但是还是存在上述问题
